app.name=LingTech

server.servlet.context-path=/shop

spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true

logging.level.org.springframework.web=DEBUG