server.port=8000
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:tienda
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
application.security.jwt.secret-key=Z3VlcmNhLWVzLWxhLW1lam9yLWVzY3VlbGEtZGUtZGVzYXJyb2xsby13ZWItZGVsLW11bmRvLWVudGVybw==
application.security.jwt.expiration=3600000
application.security.jwt.refresh-token.expiration=86400000